release-process.md
When we make a new beta/stable we may have more platforms to distribute artifacts for.
=> Add a step to releases for adding more targets

ides.md
Some of the URLs were pointing to the page itself (https://forge.rust-lang.org/ides.html).
=> Fixed broken URLs on ides.html page

platform-support.md
After [removing this from the book](https://github.com/rust-lang/rust/pull/37601) I felt the urge to update it. I mostly ended up chopping out words.
I also said no_std stuff for our supported architectures has tier 3 support, which could be considered a new policy, but also a clarification of the existing. I'd be happy to remove it.
r? @alexcrichton
=> Changes to platform support description

ides.md
Several links were missing from the page. They have been updated and should now be working correctly.
=> Fix broken links on ides.md page. Closes #19.

platform-support.md
Now that `std` support is merged, it is important to advertise support for compiling Redox OS executables.
=> Add Redox OS to tier 3

platform-support.md
* clarified the bitness;
* explicitly noted the ABI which is buried in the target triples.
=> slight tweak to the MIPS64 platform notes

release-process.md
The big change here is that the prerelease testing step move forward a day to be in front of producing the beta. That's because the beta needs the new stable rust from the archives to bootstrap.
r? @alexcrichton
=> Update release steps

ides.md
The GNOME Builder IDE has had support for Rust and the Rust Language Server
since 3.22. It natively supports various rls and cargo features such as:
- Support for the cargo build system
- Auto-completion using racer via rls
- As-you-type diagnostics
- Rename symbol
- Jump to Symbol
- Symbol Tree
And upcoming 3.24 features include
- Support for rustup toolchain management
- Documentation support
=> ides.md: add information about GNOME Builder

stabilization-guide.md
cc https://github.com/rust-lang/rust/issues/40334
r? @nikomatsakis
=> extend stabilization guide with info about docs

index.md
Plurals do not use apostrophes.
=> Grammar (PR's -> PRs)

index.md, rfc-merge-procedure.md
=> add rfc merge procedure

rfc-merge-procedure.md, rustc-team-maintenance.md
This is mostly a PR that starts a list with the steps to add/remove someone from a rust-lang team.
cc @alexcrichton -- see anything missing? Any tips on what needs to happen for r+?
=> add description of how to edit teams, apply aturon's nits

index.md, release-notes.md
From https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591/33. Seems like the kind of knowledge that should be maintained.
=> Add instructions for compiling release notes

pr-triage-procedure.md
This has everything except for the rotation information and the table of team to person from the ~internal team document. This also links (granting edit permissions) to the PR triage spreadsheet. We might want to change that; not sure.
r? @aturon
=> Add PR Triage process document.

index.md
Not quite sure if we want this; but seems good. A dedicated page would probably be better but I don't quite have time for that right now, and this seems like a good start (and more likely to be up to date).
r? @aturon
=> Add link to a documentation page for Homu syntax.

infrastructure.md
I saw things about "nag" in the rust-dashboard repo, but that's not actually where nagbot's code is. I expected to find it listed here; now it will be!
cc @aturon, is everything correct here?
=> Add nagbot

pr-triage-procedure.md
@carols10cents discussed these clarifications in chat.
=> Clarifying S-waiting-on-team procedure

rustc-team-maintenance.md
When updating team rosters, it may be prudent to also update the list of reviewers that highfive uses.
=> talk about highfive in "team maintenance"

index.md, x-py.md
Rust has switched over from old makefiles to the new build system that
uses x.py to bootstrap the repo and orchestrate building, testing, and
documenting all of the components for rustc. This system isn't as well
documented for newcomers who might not know how to use it. This adds
a skeleton with common use cases that can be expanded upon in the future
as the build system evolves or adding more documentation to current
functionality.
=> Add documentation for x.py

platform-support.md
MSP430 now has a built-in target in rustc.
https://github.com/rust-lang/rust/pull/43099
=> [MSP430] Update platform support page

platform-support.md
Due to https://github.com/rust-lang/rust/pull/43303 being merged, Redox will now fulfill the description of a Tier 2 platform.
=> Move Redox to Tier 2

platform-support.md
Add Cargo check as it builds for Solaris.
Add sparcv9-sun-solaris platform (introduced with rust-lang/rust#39901).
Be more specific with Solaris versions.
=> Update Solaris platform information

feature-guide.md
Replace it with proper documentation/links.
=> remove TBD in new feature guide

rfc-merge-procedure.md
Since there have been a few followup posts requesting this, such as https://github.com/rust-lang/rfcs/pull/2052#issuecomment-333876009
=> Add "Update rendered link" to RFC merge procedure

infrastructure.md
Bringing all things 'ecosystem testing' back under the crater name as part of [crater/issues/134](https://github.com/rust-lang-nursery/crater/issues/134)
=> Update references to cargobomb with the current crater repo.

index.md
Despite the live website showing an old page, the current repository does not include the page linked here.
=> Remove mention to IDEs

infrastructure.md
That service is gone. It's been gone for awhile.
=> Remove broken link to homu.io

rustc-team-maintenance.md
Currently, the link goes to the redirect at `team.md`, but the actual file to change is `_data/team.yml`.
=> change "ream roster" link in Team Maintenance

platform-support.md
With the upcoming stable release std is officially built for and tested on Solaris.
rustc and cargo are not Tier 2 yet.
=> Move Solaris to Tier 2

x-py.md
`it's` is a contraction of `it has` or `it is`. In some cases the
contraction for `it has` does come after `for`, but here it seems clear
that this is intended to be the possessive for `it`.
I chose not to rewrap the text of the rest of the paragraph for a typo-only change.
=> Change `it's` to `its`

x-py.md
In 1126a85e87629f7ec37fc6c4fde43419f4b9947f, rust-lang/rust moved
`config.toml.example` from `src/bootstrap/` to the project root.
Instructions in rust-lang/rust were updated, but this instance was not.
=> Update stale reference to config.toml.example location

pr-triage-procedure.md
That's not needed anymore thanks to https://github.com/rust-lang-nursery/rustc-pr-tracking.
cc @shepmaster
=> Remove the "Update the spreadsheet" step of PR triage

release-process.md
Add a list of what social media sites should get release announcements.
Most of these have already been done in practice, but announcements on
the users forum have been irregular.
=> Expand "Tweet and post everything!"

triage-procedure.md
This PR adds another step to the S-waiting-on-review triage procedure: if the reviewer is inactive for more than 9 days, the label is changed to S-waiting-on-team, to bring it to the next team meeting.
Requested by @alexcrichton [on Discord](https://discordapp.com/channels/442252698964721669/443148319431065610/461578786211627008).
r? @Mark-Simulacrum 
cc @shepmaster @TimNN
=> Set S-waiting-on-team when the reviewer is inactive for 9 days

.travis.yml
There's now https on gh-pages, so shouldn't be any need for cloudfront/s3 any
more!
=> Publish to gh-pages instead of S3

triage-procedure.md
This PR introduces the `S-blocked-closed` label. (It also deduplicates / fixes some links and adds a note about mentioning triage in triage comments).
Todo:
r? @pietroalbini
=> Introduce S-blocked-closed

state-of-rust.md
This was previously fixed in #149 but got reintroduced by #150.
=> Fixed small formatting bug in State Of Rust (again).

platform-support.md
[Context](https://github.com/rust-lang/rust/issues/52715#issuecomment-409299181)
r? @aidanhs
=> Add tier 2.5 platforms

rustc-team-maintenance.md
We no longer use database migrations to manage team memberships!
=> Update rfcbot team membership docs.

triage-procedure.md
[Rendered](https://github.com/Aaronepower/rust-forge/blob/master/triage-procedure.md#state-of-rust-triage)
cc @Mark-Simulacrum
=> Add State Of Rust triage procedure

release-process.md
Multi-line commands usually don't work well when copying them into the
terminal, so switch to just oneline.
=> Make copy-pasting release initiation easier

_config.yml, _data/platforms.yml, css/style.css, index.md, other-installation-methods.md
=> feat(content): move other installation methods doc from website

_layouts/redirect.html, debugging.md, stabilization-guide.md, x-py.md
This PR adds redirects for the pages moved to the rustc guide, to avoid breaking links.
cc @Centril @RalfJung who reported the issue on Zulip
cc @mark-i-m, we'll want to do this for every page we move out of the forge
fixes #182
=> Setup redirects for moved pages

index.md
It took me a long time to track this tool down when I needed it, I'd vaguely heard of it before but couldn't remember the name. I'm not certain it fits here perfectly, but this was one of the earlier locations I checked.
=> Include link to rustup-toolchain-install-master

state-of-rust.md
As far as I can tell this feature has been removed for good.
I was wondering if there's a script to automatically update this table but didn't find one, so here's a small drive by fix!
=> State of Rust: Remove `custom_derived`

index.md
It seems that @kennytm and @pietroalbini last discussed this code in PR rust-lang/rust-forge#207. 
Are they the appropriate reviewers for this PR?
The whole story is in the commit message, as follows:
I came across The Rust Forge web page at https://forge.rust-lang.org on
March 6th 2019 and found myself looking at a very puzzling number for
the current stable release, "1.33.16666666666667", with a release date
of "March 7th 2019".
From rust-lang/rust/RELEASES.md, the page should have stated "1.33" and
"February 28th 2019". Predicted releases were similarly inaccurate.
I fixed the above bug by using `Math.floor` (rounding down) when
calculating `newReleases`, the number of 6 week periods since the epoch.
(It appeared that, from the uses of `newReleases`, it was intended to be
an integer …
=> Fix Floating Point Bug in Release Number/Date

index.md
Source code can be found at https://github.com/oli-obk/fixmeh
The list is automatically regenerated every midnight
=> Add FIXME list to the forge

platform-support.md
Related: https://github.com/rust-lang/rust-forge/issues/198
=> Update platform list: add RISC-V targets

platform-support.md, src/main.rs, tiers.yaml
Closes #198
Closes https://github.com/rust-lang/rust-forge/issues/177
Closes https://github.com/rust-lang/rust-forge/issues/186
Closes https://github.com/rust-lang/rust-forge/pull/218
Closes https://github.com/rust-lang/rust-forge/pull/197
=> Generate the platform tier table from YAML

channel-layout.md, index.md
As part of an effort to better document how `rustup` does what
it does, this is the beginning of a document explaining how Rust's
release channels are stored on `static.rust-lang.org`.  Further
explanations will be needed as time goes by, especially as `rustup`
proceeds with `profiles` or if we do end up adopting _TUF_ as
Brian's internals post suggested we might.
Signed-off-by: Daniel Silverstone <dsilvers@digital-scurf.org>
=> channel-layout: Add a channel layout document

release-process.md
This updates the release instructions for what I believe should be the preferred process for Cargo. It is not necessary to have the absolute latest commit on beta, and there have been issues in the past with Cargo's beta branch being in the wrong spot.
I'm not super confident that all the git command magic is exactly correct, it's a little tricky to test.
=> Update release instructions for Cargo.

release-process.md
These steps aren't actually being taken, so I think it would be good to remove them to reduce confusion.
For now, I'm volunteering to update the books every other week or so.  That should keep them close enough to updated for the next release (I'll shoot for roughly a week before release).  If there are broken links or other test failures, it can take days or weeks to get the PRs through, which can complicate things.  Worst case, if some changes are missed that really need to be in a release, they can be backported to beta.
=> Update release instructions for books.

index.md
Some details on this dashboard: https://www.reddit.com/r/rust/comments/9erknj/rustup_components_history/
=> Add components availability history link

index.md
It seems apropriate to add a link to Pontoon here.
Based on discussion in https://internals.rust-lang.org/t/translating-the-stdlib-docs/10384
=> Add Rust Pontoon link for translators

other-installation-methods.md, releases.md, rfc-merge-procedure.md, rustc-bug-fix-procedure.md, rustc-team-maintenance.md, triage-procedure.md
`prettier --write --prose-wrap always *.md` splits reference links across lines, breaking them.
`preserve` should be used instead:
```bash
$ prettier --write --prose-wrap preserve *.md
```
=> Fix broken reference links

triage-procedure.md
On 2019-07-03 there was a Discord meeting on `#triage-wg` that discussed some changes to the triage process. This PR updates the Forge documentation to reflect said changes.
=> Update Triage documentation to reflect 2019-07-03 meeting

index.md, infrastructure.md, toolstate.md
Note that I don't know if the rules I am stating here reflect reality. This is based on about a year of empirical observation of what CI is doing. I tried to get someone to make an authoritative statement by filing https://github.com/rust-lang-nursery/rust-toolstate/issues/3, but that didn't work, so now I am trying the alternative strategy of just saying something and relying on people to correct me if what I say is wrong. ;)
In particular, I am not sure if it is true that *all* "toolstates" are ignored for releasing nightlies.
Cc @kennytm @pietroalbini 
Fixes https://github.com/rust-lang-nursery/rust-toolstate/issues/3. Fixes https://github.com/rust-lang/rust-forge/issues/235.
=> describe toolstate system

js/index.js
This line from the old code somehow made it through, and breaks the JS currently as `.tools-no-breakages-header` no longer exists.
=> Removed unneeded JS query

.travis.yml, js/index.js
I made a mistake, apparently the original `js/index.js` changes were lost in all the rebasing. This adds the correct and tested JS. This also adds caching for mdbook as the builds are far too long.
=> Actually fixed JS

js/index.js
IIUC, based on the rules in `checktools.sh`, Tue before release is 41, Wed is 0.  The check is `-ge 35`.  35 is the *Wednesday* of the prior week.  The current forge site says "no tools breakage starts Aug 6", which is Tuesday. But a tool broke today, so I believe it starts tomorrow.
=> Fix off-by-one in toolstate breakage week start.

src/release/platform-support.md
Haiku now provides both `rustc` and `cargo` in their latest 1.35.0 release, see: https://github.com/haikuports/haikuports/blob/master/dev-lang/rust/
=> Check rustc and cargo for Haiku

src/infra/channel-layout.md
Within the current channel-layout documentation, the documentation states that
the table `renames.rustfmt` has a `to` field with the text `rustfmt`.
The actual table [e1] however contains the text `rustfmt-preview`.
This makes sense as the rename would otherwise point to itself.
[e1] An example of an actual table can be found here: http://static.rust-lang.org/dist/channel-rust-1.38.0.toml at line 11919 which states:
```toml
[renames.rustfmt]
to = "rustfmt-preview"
```
=> Rustfmt's to field points to rustfmt-preview, instead of rustfmt.

src/release/triage-procedure.md
When triaging, we should not ping on PRs proposed fcp or nominated.
=> Update triage links

src/SUMMARY.md, src/release/rollups.md
This PR is a continuation of #87 with what @Centril has written about the current rollup procedure.
r? @Centril
=> Add Rollup Procedure

src/release/platform-support.md
Since there are some bare metal arm platforms in Tier 2, this sentence is a
bit misleading.
=> Modify "bare metal" hint

src/compiler/steering-meeting.md
r? @nikomatsakis 
The link could also be directly to the t-compiler stream. Let me know if you prefer that.
=> Add missing Zulip link to steering-meeting document

blacksmith/src/lib.rs
Matching the naming convention in [`package_vers`](https://github.com/rust-lang/rust/blob/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/bootstrap/lib.rs#L973-L991) used in the [`PlainSourceTarball`](https://github.com/rust-lang/rust/blob/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/bootstrap/dist.rs#L1075-L1076) dist step.
Closes #263.
=> Fix src download links.

README.md, js/index.js, src/README.md
The JS current errors on other pages because it can't find the `stable-version` element. This has no actual effect in practice, but is annoying to have an error in the console and would prevent us adding potentially more JavaScript for other pages in the future.
=> Fix JS error on other pages and use Standard formatting

src/SUMMARY.md, src/libs/README.md, src/libs/maintaining-std.md
Recently in Libs we've been talking about putting together some docs with various things we try to keep in mind when working on `std` (inspired by [.NET's runtime developer guide](https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-code-guide.md)), and we thought the forge here would be a good home.
This PR is an attempt to bootstrap that doc. There's not a lot here yet, and what is there is probably both incomplete and plain incorrect :) It's just a starting point to iterate on, so any suggested corrections/enhancements would be greatly appreciated! Any thoughts on organization would also be good.
cc @rust-lang/libs 
[Rendered](https://github.com/KodrAus/rust-forge/blob/libs/src/libs/maintaining-std.md)
=> An initial section for libs docs

src/release/platform-support.md
- a required [TLS fix](https://reviews.freebsd.org/rS342113) has landed a year ago
- it has been available in FreeBSD packages for a while
- [recent build log example](http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p518178_s355024/logs/rust-1.39.0.log)
=> platform-support: tick aarch64-unknown-freebsd

src/release/platform-support.md
DragonFly BSD only supports x86_64 right now. i386 was removed a while ago.
=> Remove i686-unknown-dragonfly

src/release/platform-support.md
This patch remove duplicated `nvptx64-nvidia-cuda` line in https://forge.rust-lang.org/release/platform-support.html
=> Remove duplicated line in platform list

.gitignore, blacksmith/src/lib.rs, blacksmith/src/main.rs
Before this PR, the preprocessor fetched the channel manifests to figure out the stable version and the available targets every single build. This was annoying especially when running `mdbook serve`, which rebuilds the content automatically every time a file changes on disk.
This PR caches that information in an ignored .blacksmith-cache.json file, with a TTL of an hour. Within the hour the old data will be reused, and after that amount of time new data will be fetched to refresh the cache.
This shouldn't affect CI or other production builds, as the repository as a whole isn't cached between builds.
r? @XAMPPRocky
=> blacksmith: cache the manifests and targets for an hour

src/chat/zulip.md
This fixes the link to the chatroom by adding https:// in front of it.
=> Fix link to Zulip chat room

src/libs/maintaining-std.md
Per discussion in https://paper.dropbox.com/doc/Specialization-Review-2020-02-03--AuBwAqGbsHDmBlBy~XUlmqUcAg-jFYgiknJi6j00SbN83dWX.
r? @nikomatsakis 
cc @rust-lang/libs @rust-lang/compiler-contributors 
cc https://github.com/rust-lang/rust/pull/68970
cc https://github.com/rust-lang/rust/pull/68472
=> Note the moratorium on new uses of specialization in the standard library

build.bash
This ended up being a little more complicated than I wanted because it
allows for CARGO_TARGET_DIR to be both a relative and absolute path. It
should work anywhere with bash installed.
=> Allow setting CARGO_TARGET_DIR

blacksmith/src/lib.rs, src/README.md, src/chat/zulip.md, src/compiler/README.md, src/infra/toolstate.md, src/lang/rfc-merge-procedure.md
The rustc-guide is being renamed to the rustc-dev-guide. The discussion is in rust-lang/rustc-guide#470.
This PR revises rustc-guide to rustc-dev-guide in the `blacksmithc/src/lib.rs` and the Markdown files.
Transition tracker: rust-lang/rustc-guide#602
=> Update rustc-guide to rustc-dev-guide

src/release/platform-support.md
Document Apple 32bits targets as Tier 3. This should go along with the release of Rust 1.42 which will be the first concerned release.
Tracking issue: rust-lang/rust#67724
r? @pietroalbini
=> Demote Apple 32bits targets to Tier 3

src/libs/maintaining-std.md
I was made aware of this [here](https://github.com/rust-lang/rust/pull/69617#issuecomment-599434746). I guess this note is useful in this document.
=> Add note about CCing `@rust-lang/wg-const-eval` for const fn PRs

src/compiler/README.md
`rustc` was renamed to `rustc_middle` in https://github.com/rust-lang/rust/pull/70536.
=> Fix link to internal rustc documentation

src/release/process.md
Most days used `##`, except Wednesday and Friday used `#`.
=> release process: sync header levels

src/release/platform-support.md
Compiler support was merged [here](https://github.com/rust-lang/rust/pull/66661).
There is an issue tracking this support [here](https://github.com/rust-lang/rust/issues/62117).
Stable is already built with `riscv64gc-unknown-linux-gnu` target support. To try it see [my PR adding support to cross](https://github.com/rust-embedded/cross/pull/413).
=> platform-support: add tier3 riscv64gc-unknown-linux-gnu

src/README.md
Adds a section providing links to each repositories list of issues that are marked as need help and/or good first issue. I started with this small list, but we can also add other projects.
=> Add Help Wanted section to index.

src/infra/team-maintenance.md
Updates a few things that I'm aware of:
- the website team roster is now driven by the team repo
- rfcbot is now driven by the team repo
- bors is now driven by the team repo
- highfive repo has moved
=> Update team maintenance.

src/compiler/membership.md
I wasn't sure exactly where the infra link should go but I think that makes sense.
=> Fix some broken links in membership.md

src/release/rollups.md
This has the advantage that I can copy-paste the entire command, and do not have to manually select the label in the list.
=> rollup: set label via bot

src/release/platform-support.md
This updates the platform tiers to the best of my knowledge.
**Tier 2 new**
* aarch64-unknown-none-softfloat  https://github.com/rust-lang/rust/pull/64589
* armv7-unknown-linux-gnueabi https://github.com/rust-lang/rust/pull/63107
* armv7-unknown-linux-musleabi https://github.com/rust-lang/rust/pull/63107
**Tier 3 removed**
* x86_64-unknown-bitrig https://github.com/rust-lang/rust/pull/60775
* wasm32-experimental-emscripten https://github.com/rust-lang/rust/pull/63649 (or https://github.com/rust-lang/rust/pull/65251)
**Tier 3 new**
* aarch64-apple-tvos  https://github.com/rust-lang/rust/pull/68191
* x86_64-apple-tvos  https://github.com/rust-lang/rust/pull/68191
* armv7a-none-eabihf  https://github.com/rust-lang/rust/pull/68253
* i686-unknown-uefi …
=> Update platform tiers.

src/release/platform-support.md
To the best of my knowledge, this does not reflect the actual status of these platforms. These platforms aren't built on CI, and they seem to just be regular tier 3 platforms.
It is difficult to tell from the original PR (#157) what the context was. I don't see any evidence that these were being built at the time.
- cloudabi: Only [`x86_64-unknown-cloudabi`](https://github.com/rust-lang/rust/blob/82911b3bba76e73afe2881b732fe6b0edb35d5d3/src/ci/docker/dist-various-2/Dockerfile#L95) is built. Some of these were (erroneously?) added to the manifest, but were later removed in https://github.com/rust-lang/rust/pull/55187 (there is still one vestigial entry for `aarch64-unknown-cloudabi`).
- `powerpc-unknown-linux-gnuspe`: This was added as a "disabled" Dockerfile in …
=> Remove tier 2.5.

src/libs/maintaining-std.md
cc @rust-lang/libs @rust-lang/wg-const-eval 
In https://github.com/rust-lang/rust/pull/69373#issuecomment-591041786 it was noted that stabilizing the `const`-ness of functions should include the WG. Should this only really be necessary when there are internal unstable const features used in those stabilizing functions?
@ecstatic-morse offered [some guidelines](https://github.com/rust-lang/rust/pull/69373#issuecomment-591070340) on things to keep in mind when stabilizing `const` functions with internally unstable features. Would you like that to be included here?
=> Stabilizing const functions

js/index.js, src/README.md
The *No Tools Breakage Week* table didn't make sense to me. It currently says the "beta 1.44" no breakage week is May 27 &ndash; June 2. But beta 1.44 was cut a long time ago and is about to become stable 1.44. The relevant version number for the May 27 &ndash; June 2 date range is the 1.45 beta being cut.
Also the "Channel" column didn't seem applicable because every row is talking about a beta cut.
This also fixes a place that the js thought there were more rows in the table than the markdown did, causing a runtime type error.
<br>
<p align="center">
<br>
</p>
<p align="center">
</p>
=> Fix correspondence between versions and dates in No Tools Breakage table

src/release/platform-support.md
Update notes for aarch64-unknown-redox in platform-support.md.
It makes it easier to read in my opinion.
=> Update notes for aarch64-unknown-redox in platform-support.md

src/release/platform-support.md
Update platform-support.md to include mipsel-sony-psp
I took the name from https://github.com/rust-lang/rust/pull/72062.
I have no idea if it has std, rustc, cargo. I assumed it's Tier 3. @overdrivenpotato should know the details. :)
=> Update platform-support.md to include mipsel-sony-psp

src/release/platform-support.md
I am not sure about details.
@dylanmckay would you be able to help out with them? Does it support core, alloc, or std?
AVR support PR: https://github.com/rust-lang/rust/pull/69478
=> Add avr-unknown-unknown to platform-support.md

src/release/platform-support.md
The target spec for `thumbv7a-uwp-windows-msvc` was added to the Rust codebase in https://github.com/rust-lang/rust/pull/72133. It should be documented as a Tier 3 target once added.
`libstd` built and worked out of the box, but some crates built only in `--release` builds. Therefore, the usability I assume is `?`.
=> Add thumbv7a-uwp-windows-msvc to platform-support

src/release/rollups.md
Also makes a small edit to split into two sentences.
=> Fix missing word in rollups.md

src/libs/README.md
Adds a note about the `#t-libs` stream on Zulip, based on https://rust-lang.github.io/compiler-team/about/chat-platform/
cc @rust-lang/libs
=> Add section on where to find libs team

src/infra/other-installation-methods.md
#source is not a valid heading link
=> Fix contents link on other-installation-methods

src/SUMMARY.md, src/compiler/notification-groups.md
Sample PR. I'm considering moving the list of steps into the compiler-team repository, though, as a template tracking issue. Maybe that'd be better.
=> describe how to create a notification group

src/release/platform-support.md
- i686 and x86_64 updated to kernel 2.6.32 and glibc 2.11 in <https://github.com/rust-lang/rust/pull/74163>.
- Targets that use crosstool-ng or similar now list their configured support.
- Targets that are built with Ubuntu 16.04 toolchains now list kernel 4.4 and glibc 2.17.
- Targets that are built with Ubuntu 18.04 toolchains now list kernel 4.15 and glibc 2.27.
- Tier-3 targets still have no specified support, since they don't build dist.
=> Platform Support: update kernel/glibc versions for linux-gnu targets

src/compiler/steering-meeting.md
link to proposals page so that the main steering-meeting page has "everything" in one place.
(The motivation for this is to provide a usable target page for other pages
outside forge, such as the compiler-team site, that want to explain the steering
meeting.)
=> link to proposals page from main steering-meeting page

src/release/platform-support.md
This reflects the change in rust-lang/rust#74639.
=> Downgrade glibc to 2.11 for ppc, ppc64 and s390x

src/release/platform-support.md
* aarch64-apple-darwin: https://github.com/rust-lang/rust/pull/74541
* thumbv4t-none-eabi: https://github.com/rust-lang/rust/pull/74419
* RISC-V GNU/Linux https://github.com/rust-lang/rust/pull/72973 (no change?)
- Note: I think there is some ambiguity in the table. A check-mark for `rustc` can mean "it compiles" and also mean "automated builds with rustup artifacts".
* x86_64-unknown-illumos:  https://github.com/rust-lang/rust/pull/71272
=> Some platform updates.

src/compiler/prioritization/procedure.md
Small fix, in our procedure to-announce are added to issues and prs so after we are done we need to clean both.
r? @XAMPPRocky
=> Prioritization WG: remove to-announce issues and also PRs

src/libs/maintaining-std.md
- Include a link to `hashbrown` with a description of how `#[inline]` works
- Add a note about breaking changes to stable behavior
- Add a note about `#[may_dangle]` (after https://github.com/rust-lang/rust/pull/75648)
=> Some Maintaining Std Docs

src/compiler/reviews.md, src/libs/maintaining-std.md, src/release/rollups.md
This adds some guidance on setting rollup status and priority for the rust-lang/rust repo.
I waffled where to place this. I'm fine with moving it wherever. The rollups page was a high candidate, or a new page in the release or infra sections? No one group really "owns" the rust-lang/rust repo, so it is not really clear where it belongs.
I fully expect there to be some changes here, this is just a rough sketch that I wanted to start some discussion. This is based on some discussion at:
- https://github.com/rust-lang/rust/issues/74193
- https://internals.rust-lang.org/t/rollup-never-always-guidance/11827
- https://github.com/rust-lang/homu/issues/93
=> Add some guidance on rollups and priorities.

src/release/process.md
We want to avoid publishing nighlies with a misleading version number. When we
promote master to beta, all subsequent commits on master should have an
incremented version number, but this is currently not quite true, as during
release week we first promote and then later bump version numbers.
cc @rust-lang/release 
r? @pietroalbini
=> Document new release branching

src/libs/maintaining-std.md
Based on a soundness issue with `SyncOnceCell` introduced when we added a `#[may_dangle]` attribute without also informing dropck that we logically own the value: https://github.com/rust-lang/rust/issues/76367
cc @matklad @m-ou-se
r? @RalfJung
=> Add note about PhantomData and dropck

src/release/process.md
Just a small formatting/markdown fix. [Rendered diff](https://github.com/rust-lang/rust-forge/pull/436/files?short_path=c6102a0#diff-c6102a095154b31981d16ec43db953ca) says it all.
=> Fix incorrect backtick usage in inline code

src/libs/maintaining-std.md
There have been a lot of bugs fixed in intra-doc links lately and they are being stabilized in the next release. Additionally, almost all intra-doc issues are caught in the PR build, before they get to bors; the only exceptions I can think of have to do with `cfg(platform)`, which should be comparatively rare (https://github.com/rust-lang/rust/issues/76526) and no more likely to fail than linkcheck failures.
=> Don't single out intra-doc links as causing rollups to fail

src/archive/fott.md
Username previously listed for @Gankra linked to a redirect github page.
This was noticed by @Moongoodgirl who mentioned it on Freenode/##rust.
~~I have also replaced the pronouns on the page with gender neutral
'they'. However, the ideal solution would be to get in touch with Alexis
and ask them what pronouns they would like on the Friends of the Tree page.~~
@Gankra herself said she goes by she/her, update pronouns in FoTT page to match.
Reported-by: @Moongoodgirl
Signed-off-by: @aoeixsz4
=> Update username/github link of Gankra

src/libs/README.md, src/libs/maintaining-std.md
This PR makes a few drive-by changes to our Libs docs:
- Links to the new `rust-lang/libs-team` repository.
- Adds an example of private specialization and removes the note that we can't use it (now that we have `min_specialization`)
- Stubs out a section on const generics.
r? @scottmcm on the specialization comments. Do those look good to you from a libs-impl perspective?
=> Updates to Libs docs

src/compiler/prioritization/procedure.md
That part of the process lives now in the `Follow ups from previous meeting` section.
And have also modified the mentions to working groups on the notify compiler team section.
r? @XAMPPRocky
=> Remove wg checkins text from notify team section

src/release/triage-procedure.md
It was `updated-desc` before, but all the others are `updated-asc` which
is more helpful.
cc @Dylan-DPC
=> Fix status tag link in triage procedure

src/infra/docs/rustc-ci.md, src/infra/service-infrastructure.md, src/release/README.md, src/release/rollups.md
I found that the links weren't updated when reading the rollup procedure :)
=> Update links to the bors queue

src/libs/maintaining-std.md
`MaybeUninit` no longer has a `.read()` function; it was renamed to `.assume_init_read()`. But it also has a `.assume_init_drop()` now, which is a better fit for this example.
=> Update example for new interface of MaybeUninit.

src/release/process.md
This updates the release process to follow the changes in https://github.com/rust-lang/rust/pull/79133.
r? @Mark-Simulacrum
=> Update release process for rust-lang/rust#79133

src/compiler/prioritization/procedure.md
We don't really do any of these things, so it doesn't make sense to have that documented there.
cc @rust-lang/wg-prioritization
=> Remove toolstate and performance stats checks

src/platforms/zulip.md
The Github repository references that describe which repositories have supported short linkifier notations were outdated for chalk, ena and polonius.
All three projects are no longer in rust-lang-nursery but in rust-lang. The resulting links will still work but might confuse new users.
The current linkifier settings for rust-lang.zulipchat.com already use the updated link for chalk but not for the other two.
Addresses the first part of #476 .
=> Fix outdated repository references for linkifiers

src/libs/maintaining-std.md
This is something we've done in the past to try reduce noise from deprecated items.
=> Add note about when a feature is deprecated

src/release/rollups.md
It's outdated since https://github.com/rust-lang/homu/pull/114.
=> Remove outdated instruction about `rollup` label

src/compiler/membership.md
I thought we had gotten rid of them all 😄
=> rustc-guide -> rustc-dev-guide

src/compiler/prioritization/procedure.md
cc @rust-lang/wg-prioritization 
This adds to the filters `T-doc`, `T-core` and `T-cargo`. I've just seen some issues popping up due to not filtering those teams.
=> Filter out more teams on No team prioritization checks

src/README.md
Link on current master (shows 0 open, 0 closed):
https://github.com/rust-lang/www.rust-lang.org/labels/good%20first%20issue+no%3Aassignee
Link in this commit (shows 0 open, 24 closed):
https://github.com/rust-lang/www.rust-lang.org/issues?q=is:open+label:%22good+first+issue%22+no:assignee
=> Fix broken link to rust-lang/www.rust-lang.org good first issues

src/infra/toolstate.md
I looked here for how to do so, and it wasn't here, so I asked on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/237824-t-lang.2Fdoc/topic/How.20to.20Update.20Reference.20Submodule.3F) and put the answer into this pull request.
=> Add "Updating tools" section to toolstate chapter

src/release/process.md
[`publish.py`](https://github.com/rust-lang/cargo/blob/master/publish.py) was added a while back to (hopefully) help make it easier and more reliable to publish new releases of Cargo. 
I'm not sure if these instructions are detailed enough. Should the explicit tagging steps be specified? Should it make it clear that this should be run on the stable branch, **and importantly** run `git submodule update` to ensure the correct submodules are checked out? (I believe some mistakes in the past were made because the wrong checkout was published.)
Let me know if more detail should be added.  I'm not too familiar with the exact steps you take for this.
=> Update release process for Cargo.

src/compiler/prioritization/procedure.md
Hi,
I've tried clarifying a bit the suggested timeline after the compiler meeting. 
r? @spastorino does it sound better?
thanks
=> Clarify after meeting tasks

src/infra/other-installation-methods.md
There is no standard package manager for MacOS, there are at least
three popular ones, and all of them have Rust available.  This pull
requests adds some of the other popular package managers.
=> Add MacPorts and pkgsrc package manager options

README.md, book.toml, src/SUMMARY.md, src/release/backporting.md
Hi,
I'm not sure where stable backports are explained, so I've tried rewording the backporting page adding them.
Since now the page is about generic backporting I've renamed the .md file and updated the index and the redirection for clients landing on `./release/beta-backporting.html`
Thanks for having a look at this!
r? @Mark-Simulacrum @XAMPPRocky
=> Mention stable backporting procedure

src/release/process.md
This PR includes miscellaneous updates to the release process to reflect what I'm doing for the 1.52.0 release. The changes are:
1. Update the `T-` in the release day schedule to better reflect how long `promote-release` takes nowadays.
2. Remove posting on Reddit and HN from the list of things to do after the release.
3. Expand the documentation on Wednesday's steps, better reflecting what I did this cycle and adding guidelines on what to do for `bootstrap` cfgs. The guidelines would've been really useful when I started doing releases, and I hope they'll be useful when we onboard new people to doing releases.
Notably, commits for (1) and (2) were already included and reviewed in https://github.com/rust-lang/rust-forge/pull/517. Once this is merged I'll rebase …
=> Update the release process as of 1.52.0

src/release/process.md
* Updated changing the channel to `src/ci/channel`
* Used `git@github.com:rust-lang/$repo` instead of `origin` or `rust-lang`, as those could point to different places (for example I don't have `rust-lang` as a remote and for cargo `origin` uses HTTPS for me
* Replaced finding the branch point with a one-liner:
```
git log --merges --first-parent --format="%P" -1 master -- src/version | awk '{print($1)}'
```
* `--merges --first-parent` shows the merge commit instead of the commit actually changing the file
* `--format="%P"` outputs just the sha(s) of the parent commits in the log -- this allows to detect which is the commit *before* the merge commit bumping the version
* `-1` only includes the first entry
* `master` forces the log to be on the master branch, even if the working directory …
=> Update release process

src/release/triage-procedure.md
S-blocked and S-blocked-closed were merged into S-blocked, and
S-inactive and S-inactive-closed were merged into S-inactive.
See the WG-triage meeting log for details on this change [1].
[1]: https://zulip-archive.rust-lang.org/242269treleasetriage/01551Meeting10032021.html#229694397
cc @Dylan-DPC
=> Update Triage Procedure from deletion of S-blocked-closed and S-inactive-closed

src/release/process.md
This PR updates the release process following up on the addition of the bump-stage0 tool in the rust-lang/rust monorepo, making these changes:
* Downloading artifacts from dev-static.rust-lang.org is not supported anymore, so the step to bump stage0 during beta promotion is removed. This doesn't have any practical effect, as we're still building the new beta with the previous beta.
* As there is no dependency anymore between promoting beta and promoting stable both are moved to the same day, bringing the master bootstrap update one day earlier.
* The step to update the beta bootstrap compiler after the release was updated to use the tool.
r? @Mark-Simulacrum 
cc https://github.com/rust-lang/rust/pull/88362
=> Update the release process with bump-stage0

src/release/process.md
This uses an automated method for getting the cargo version to tag instead of determining the version manually.
=> Avoid manual step in cargo release process.

src/release/backporting.md
The only substantive change here is to add the step of changing the milestone of backported PRs.
However, I felt inclined to rework it so that it is presented as series of clearly enumerated steps. Hopefully that seems like an improvement?
=> Update beta backport process.

src/platforms/zulip.md
Accounts for migration to web-public streams.
=> Update read-only view on Zulip

src/README.md
I believe the current heading “Release Date” is hard to understand; the first obvious interpretation is “The version currently in this channel was released to this channel on…”, which is falsifiable since non-stable channel dates are in the future, but it's still a speedbump. I believe that relabeling it to “Will be stable on” will make the table easier to understand by newcomers.
=> Change “Release Date” to “Will be stable on”.

src/compiler/reviews.md
Noticed the missing closing paren while reading, and also thought it would be good to mention subtrees alongside submodules given that multiple tools have switched from submods to subtrees.
=> fix typo, list subtrees in priority gudiance

src/docs-rs/add-dependencies.md
See https://github.com/rust-lang/docs.rs/issues/1718
- dependency to docker and docker-compose added
- docs.rs needs to be cloned before you can change to /path/to/docs.rs
- "docker build —tag build-env ." must be run in directory linux inside crates-build-env
- in docs.rs the .env.sample needs to be copied to .env
- environment variable DOCS_RS_LOCAL_DOCKER_IMAGE is outdated and must be replaced with DOCSRS_DOCKER_IMAGE
- lint.sh is in the root directory of crates-build-env
- new Ubuntu version
- setting the crate directory moved to the beginning
- mentioned alphabetical order when adding package name of dependency
=> Small fixes, missing steps added, copy-paste-able

src/infra/service-infrastructure.md
The document says there's a "[collector] and a [web frontend + bot]", but confusingly the bot docs are with the collector, so let's be a little more explicit.
=> say where the rust-timer bot command docs are

js/index.js, src/README.md
This helps teams plan for when we're close to cut off points, rather than
planning around the stable date (which is important only for backports, really).
=> Add branch date to index page

src/release/process.md
This assumes that https://github.com/rust-lang/promote-release/pull/46 and https://github.com/rust-lang/promote-release/pull/45 have been merged and a few scripts updated/added in the simpleinfra repository to account for them. (Should be pretty easy to do, but is a little bit of work).
r? @pietroalbini
=> Update the release process for latest automation

src/SUMMARY.md, src/compiler/cross-team-collaboration.md
Add procedures for other teams who would like to raise issues for the compiler team to fix. Based on discussion in a [compiler team planning meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bplanning.20meeting.5D.202022-07-29). 
cc @wesleywiser @pnkfelix @jackh726 @yaahc 
cc rust-lang/compiler-team#527
=> compiler: cross-team collaboration

src/release/backporting.md, src/release/process.md
Due to https://github.com/rust-lang/rust/pull/100591
There are a few changes in the release process and how changes are backported to beta, mostly around running `./x.py run replace-version-placeholder` at specific points. This PR updates the document so that it is followed for future releases.
=> Changes reflecting the new placeholder system for stabilizations

src/infra/channel-layout.md, src/infra/docs/rustc-ci.md, src/infra/toolstate.md
RLS has been removed as of https://github.com/rust-lang/rust/pull/100863. The following mentions are no longer needed.
=> Remove mentions of RLS

src/infra/docs/rustc-ci.md, src/infra/toolstate.md
This just updates some outdated information on how CI and the toolstate system works.
Closes #653
=> Update CI and toolstate docs.

src/compiler/membership.md, src/compiler/reviews.md, src/infra/service-infrastructure.md, src/infra/team-maintenance.md, src/libs/maintaining-std.md, src/release/rollups.md, src/release/triage-procedure.md
As of https://github.com/rust-lang/triagebot/pull/1656, triagebot is replacing highfive. This PR updates the documentation to accommodate this change.
=> Update for highfive transition

src/infra/docs/dev-desktop.md
Users can connect to the dev desktops using their hostnames. The documentation has been adjusted to include their fully qualified domain names.
=> Clarify how to connect to dev desktop

src/libs/maintaining-std.md
Fix a typo in src/libs/maintining-std.md
=> Fix a typo in src/libs/maintining-std.md

src/SUMMARY.md, src/infra/docs/cdn.md
The documentation describes the current state with the most important CloudFront distributions. The motivation to document this now is that we are planning to introduce a second CDN, which we can collaborate on by updating this document.
=> Create documentation for CDNs

.github/workflows/deploy.yml
This fixes the CI build. The previous action was failing because it was trying to install the aarch64 binaries. This switches to a slightly simpler setup that just downloads mdbook and uses `simpleinfra/github-actions/static-websites` to deploy to gh-pages instead.
Closes #664
=> Fix mdbook deployment

src/infra/docs/dev-desktop.md
Two new dev-desktops have been deployed to Azure. Their hostnames, architecture, and location have been added to the documentation.
=> Add new dev-desktops to documentation

src/SUMMARY.md, src/infra/docs/aws-regions.md
The infra team recently decided which AWS regions to use by default. This decision-making process has been documented, and the decision has been added to the team's documentation.
=> Document selection of AWS regions

src/infra/service-infrastructure.md, src/infra/team-maintenance.md, src/platforms/zulip/triagebot.md
Highfive has been shut down and archived, so I don't think this documentation is needed anymore.
=> Remove mentions of highfive.

src/infra/docs/dev-desktop.md
It's clearer and avoids having people with access already think they need to ask for it.
=> Mention that people on some teams automatically have access

src/docs-rs/self-hosting.md, src/infra/other-installation-methods.md
Update other installation methods for Unix compatible OSes to use TLS v1.2 consistently with https://github.com/rust-lang/rustup/blob/843459f893091f89b2dd5c7a977da1b3eb28df1b/www/index.html#L31
See https://github.com/rust-lang/www.rust-lang.org/pull/1823#issuecomment-1595868324 for more information on why it is useful. TLDR: this allows to avoid MITM attacks when users are installing Rust using `rustup-init.sh`.
See similar PR to rustup repo: https://github.com/rust-lang/rustup/pull/3385
Closes https://github.com/rust-lang/rust-forge/issues/684
=> update installation methods to use TLS v1.2

src/triagebot/no-merge.md
=> Document added options for triagebot `no_merges`

src/community/survey-faq.md, src/compiler/prioritization/procedure.md, src/compiler/steering-meeting/how-to-run-planning.md, src/docs-rs/self-hosting.md, src/infra/docs/bors.md, src/platforms/twitter.md, src/release/process.md, src/triagebot/pr-assignment.md
This fixes a few broken links on the site.
=> Fix some broken links.

src/platforms/zulip.md
Follow up to https://github.com/rust-lang/rust-forge/pull/699#pullrequestreview-1599108516
=> Show that zulip linkifiers work for all repositories within `rust-lang`

src/SUMMARY.md, src/triagebot/review-requested.md
Implementation PR: https://github.com/rust-lang/triagebot/pull/1733
=> Add documentation for review request handling feature

triagebot.toml
This adds a triagebot configuration, primarily to set up auto-assignment and to support `r?`. I do not intend that the assignment is correct, since I suspect most of these teams would prefer some subset. However, I don't particularly want to hunt down every team to make a decision, so my intent is that the teams can post PRs to update the assignment to whoever they want (or just use manual `r?`).
=> Add triagebot config.

src/governance/council.md
Both mdbook and GitHub strip the `'` character in the anchor link.
=> Fix broken link in council page.

src/docs-rs/add-dependencies.md
Fix typo in documentation: rustops ⇒ rust-lang
(it appears the original name was rust-ops rather than rustops, but the repository
now redirects to rust-lang/crate-build-env entirely)
=> Fix typo in documentation: rustops ⇒ rust-lang

.github/workflows/deploy.yml, blacksmith/Cargo.lock, blacksmith/Cargo.toml, blacksmith/src/main.rs
This updates all dependencies, including the version of mdbook used to build the site.
I dropped the use of `clap` since it was not really serving much purpose.
=> Update all dependencies

src/infra/docs/dev-desktop.md
Users can request the installation of new system packages by opening a pull request against the rust-lang/simpleinfra repository. The process has been documented in the user guide for the dev-desktops.
=> Document how to add packages to dev-desktops

src/libs/maintaining-std.md
Since that feature has been stable for some time
=> [maintaining-std.md] remove section referencing `min_const_generics`

src/compiler/mcp.md
Sibling PR to https://github.com/rust-lang/triagebot/pull/1747
Context: I'm trying to encourage a homogenous syntax to raise and resolve concerns in MCPs, so it'll be easier to parse the github comments and summarize the consensus status of the MCP.
As mentioned in the other PR, the suggested syntax mimics the FCP but will not activate anything nor will emit errors. It's just formalizing a syntax.
[
Rendered](https://github.com/rust-lang/rust-forge/blob/70f9c722d656588210c582170dc1dfd17e6cac2c/src/compiler/mcp.md#how-does-one-register-as-reviewer-register-approval-or-raise-an-objection)
cc: @Mark-Simulacrum for a :+1:
=> Try to formalize the "concern" syntax for MCPs

src/community/survey-faq.md
Added links for our annual Rust survey results for years 2019-2022
=> Add links to past survey results

src/compiler/membership.md
Discussed between compiler contributors on Zulip
[Rendered
](https://github.com/rust-lang/rust-forge/blob/338af5b0da862ce73cd366ec28967d4c6827d87d/src/compiler/membership.md#what-it-means-to-be-a-compiler-contributor)
r? @spastorino for merge
thanks!
=> Add details about promotion into compiler contributors team

src/compiler/reviews.md
As discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Never.20Rollup.20When.20Changing.20the.20.60compiler.60.E2.80.A6.20compiler-team.23407/near/226516699) the current wording is a little ambiguous as to what the meanings of the various non-explicit rollup commands are. This attempts to make that clearer.
=> Clarify rollup meanings

src/compiler/membership.md
fixes #713 
- remove the static link list of git repos (that could get outdated)
- added link to check repos a t-compiler-contributor member has access to
=> Improve tip about git repos for t-compiler-contributors members

src/infra/team-maintenance.md
Per leadership council discussion in our last meeting, proposing a set of rules for us to approve on behalf of the project with regards to team repo administration. The goal is to largely codify the status quo, while providing opportunity for expansion of merge rights under documented guidelines.
cc @jackh726
=> Propose rules for team repo maintenance

src/SUMMARY.md, src/release/issue-triaging.md
This explains some of the existing processes around triage, and how I do it. If you have different opinions, please leave them here (though it would be nice for this not to drown in bikeshedding :3)
Some people that come to my mind here (that I remember being involved in discussions or that I see doing triage in the wild):
@saethlin @enselic @kpreid @jackh726 @pnkfelix @apiraino @matthiaskrgr @aDotInTheVoid 
some discussion:
https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Removing.20.60needs-triage.60
https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/needs-triage.20update
https://rust-lang.zulipchat.com/#narrow/stream/242269-t-release.2Ftriage/topic/E-needs-repro
https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Clarifying.20E-needs-m …
=> Create chapter about rust-lang/rust issue triaging

src/release/issue-triaging.md
Changes suggested by @apiraino in https://github.com/rust-lang/rust-forge/pull/716
cc @Nilstrieb
=> Add more links to issue-triaging.md

src/SUMMARY.md, src/platforms/calendars.md
Adds a short info about the new calendar automation. I wasn't sure where best to put it, but I think that `Platforms` is a good fit.
=> Add information about calendar automation

README.md
This adds explicit guidance that any Rust team may use the Forge, along with instructions on how to add themselves. It also explicitly mentions the merge policy, and that the infra team is responsible for overall management of the forge. This is per the decisions made in the 2024-01-19 council meeting.
Closes https://github.com/rust-lang/leadership-council/issues/47
=> Specify maintenance and ownership of the forge.

src/platforms/calendars.md
Typo that I noticed immediately after https://github.com/rust-lang/rust-forge/pull/723 was merged :facepalm:
=> Fix typo in calendars.md

src/infra/docs/rustc-ci.md
Here is a diff for example: https://gist.github.com/Kobzol/66bcd8f9c4153803c25c46966d306c13
=> Add guide on how to run a different CI job for a try build

src/SUMMARY.md, src/triagebot/pr-assignment-tracking.md, src/triagebot/pr-assignment.md
We are implementing a mechanism to track and manage pull requests assigned for review to Rust contributors.
For now, the only interface to query your work queue is the Zulip chat.
This patch starts documenting how to interact with the Zulip chat bot.
=> Add docs for tracking PRs assigned for review through the Zulip chat

src/infra/other-installation-methods.md
This adds a guide for reproducing the contents of the source tarballs that we publish on our CDN. It is designed for maintainers that are building their own Rust toolchain from source code.
=> Add a guide for reproducing the contents of the source tarballs

blacksmith/src/lib.rs, src/infra/other-installation-methods.md
Related to https://github.com/rust-lang/infra-team/issues/89.
=> Use `.tar.xz` instead of `.tar.gz` for archive links

src/infra/other-installation-methods.md
To avoid extracting the archives.
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Separate.20CI.20workflow.20for.20source.20tarballs/near/430505788
=> Use a different method to compare source tarball archives

src/SUMMARY.md, src/triagebot/transfer.md
This adds documentation for the new transfer command added in https://github.com/rust-lang/triagebot/pull/1780
=> triagebot: Add documentation for transfer command.

src/triagebot/zulip-notifications.md
Here's a small documentation update to show how to use the new nomination label (we include a placeholder to point to the nomination to specific team
See: https://github.com/rust-lang/triagebot/pull/1766 and https://github.com/rust-lang/rust/pull/119959
r? @ehuss 
thanks!
=> Update Zulip issue team nomination template

src/release/issue-triaging.md
1. Mention more label categories that are of importance 
1. Mention `PG-*` labels (→ specific project groups).
2. Mention `L-*` labels (→ specific lints).
3. Mention `-Z*` labels (→ specific unstable `-Z` compiler flags).
2. ~~Mark keywords bold / strong. With keyword I mean words (e.g., *team*) whose initial is used as the prefix of a label category (e.g., *T-*). https://rustc-dev-guide.rust-lang.org/contributing.html#issue-triage does this, too, which I found out after the fact.~~
3. Linkify label categories just like https://rustc-dev-guide.rust-lang.org/contributing.html#issue-triage.
4. Add three footnotes for "trivia" (can be used to form mnemonics :P).
5. Link to https://rustc-dev-guide.rust-lang.org/contributing.html#issue-triage.
6. Tiny style tweaks for consistency (periods, …
=> Tweak and update subsection Labels of Issue Triaging

src/triagebot/README.md
Thanks to all the work from @Kobzol, nearly everything has been transitioned to the team database, so I think this note can be removed.
=> Remove triagebot manual note.

blacksmith/src/lib.rs, src/SUMMARY.md, src/infra/archive-stable-version-installers.md, src/infra/other-installation-methods.md, src/infra/shared-standalone-installers.md
Closes https://github.com/rust-lang/rust-forge/issues/676
This PR adds a new page "Archive of Rust Stable Standalone Installers" that contains a list of tables of previous stable Rust version standalone installers.
Currently it works for all versions > 1.8. Versions <= 1.7 do not have v2 toml manifests. See Zulip for [details](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Manifest.20files.20for.20stable.20channel.20.3C.3D.201.2E7.3F/near/428281514).
@shepmaster @ojeda Is this what you had in mind?
Screenshots:
=> Add Archive of Rust Stable Standalone Installers

src/triagebot/no-merge.md
In a similar vein to https://github.com/rust-lang/rustc-dev-guide/pull/1889.
=> Use a safer command for rebasing

src/platforms/github.md
This updates the documentation on GitHub access to incorporate [RFC 2872](https://rust-lang.github.io/rfcs/2872-github-access-policy.html).
=> Update GitHub access policy docs.

blacksmith/src/lib.rs
We should document that bare archives are available for all platforms, including those that have native installers (currently only darwin and windows).
=> Document `.tar.xz` archives for platforms with installers

src/triagebot/pr-assignment.md
This doesn't seem to be documented anywhere at the moment.
=> Document `users_on_vacation`

src/infra/docs/bastion.md
I got this wrong. Hopefully this change will prevent this mistake from happening again 👍
=> specify aws region in bastion docs

src/infra/docs/dev-desktop.md
taken from [this](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.E2.9C.94.20dev-desktop-eu-1.20disk.20quota.20exceeded/near/472174888) zulip message
=> docs(dev-desktops): document available disk space

blacksmith/src/lib.rs
I added Archive of Rust Stable Standalone Installers page in https://github.com/rust-lang/rust-forge/pull/733.
Later it was pointed out to me that version 1.8.0 is listed twice on [the archive page](https://forge.rust-lang.org/infra/archive-stable-version-installers.html). My original implementation relied on my assumption that `https://static.rust-lang.org/dist/YYYY-MM-DD/channel-rust-1.minor.patch.toml` would appear only once in the https://static.rust-lang.org/manifests.txt. (It seems fine at a glance when I was implementing it.) But that is not true for 1.8.0, 1.14.0, 1.15.1, 1.49.0, which have multiple entries.
In this PR I add logic to deduplicate entries in the archive of stable standalone installers and make sure that they are printed in the correct order.
Screenshot that shows …
=> Deduplicate entries in the archive of stable standalone installers

blacksmith/src/lib.rs
Add support for stable versions before 1.8.0.
I added Archive of Rust Stable Standalone Installers [page](https://forge.rust-lang.org/infra/archive-stable-version-installers.html) in https://github.com/rust-lang/rust-forge/pull/733 and https://github.com/rust-lang/rust-forge/pull/770.
Currently it works for all versions >= 1.8.0. Versions <= 1.7.0 do not have manifests. See Zulip for [details](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Manifest.20files.20for.20stable.20channel.20.3C.3D.201.2E7.3F/near/428281514).
So in this PR I hard code the available platforms for stable versions before 1.8.0. I got the list of the supported platforms for each version by trying to download (similar to what rustup does for them). I tested that I am able to download the …
=> Add support for stable versions before 1.8.0

src/release/process.md
This is to not forget to remove boostrap references like `check-cfg` lint config in `Cargo.toml` files:
https://github.com/rust-lang/rust/blob/9618da7c9995a673af4841149ba2d1f53b69dd92/library/core/Cargo.toml#L46-L47
r? @cuviper
=> Include toml files when searching for `#[cfg(bootstrap)]`

src/lang/rfc-merge-procedure.md
This step is now automated by triagebot (see https://github.com/rust-lang/triagebot/pull/1848).
=> Remove RFC rendered link step

src/release/issue-triaging.md
based off of disscussion in
https://rust-lang.zulipchat.com/#narrow/channel/242269-t-release.2Ftriage/topic/Please.20make.20sure.20to.20label.20ICEs.20by.20source.20region
=> add instructions for triaging ICE issues

src/release/process.md
Now that https://github.com/rust-lang/rust/pull/132649 got merged (thanks @klensy!) we should add a step to the master update recommending to run the command and fix the lints it points out, to avoid the failure happening in CI.
r? @Mark-Simulacrum
=> Add note about running clippy ci during the release process

src/triagebot/review-submitted.md
There's only one `reviewed_label`, not a list of them. Also see the [code](https://github.com/rust-lang/triagebot/blob/d7d4babe564e264ea4824bba1ba55a8088d8a9fd/src/config.rs#L305).
=> triagebot: fix review-submitted docs

src/triagebot/transfer.md
This clarifies that the `@rustbot transfer` command requires the destination to also have triagebot enabled.
=> Clarify triagebot transfer limitation

src/compiler/mcp.md
Fixing a typo when suggesting the syntax to raise concerns on compiler MCPs
=> Fix mcp concern syntax hint

src/SUMMARY.md, src/triagebot/merge-conflicts.md
This adds the documentation for https://github.com/rust-lang/triagebot/pull/1856
=> Triagebot: merge-conflicts

src/infra/team-maintenance.md
The `repo` directory manages both access as well as the configuration and automation of repositories. Since all repositories are now managed by the team repo and we are adding more and more automation, it makes sense to give the infra-admins the authority to approve and merge these configuration changes, while permission changes still need to be approved by the team-repo-admins.
=> Grant infra-admins permissions for repo changes

src/SUMMARY.md, src/triagebot/bot-pull-requests.md
cc https://github.com/rust-lang/triagebot/pull/1866
=> Add docs for bot PR triagebot handler

src/compiler/reviews.md
Discussing this was proposed in: https://github.com/rust-lang/compiler-team/issues/444. The actual discussion took place [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202021-07-16.20compiler-team.23444).
[Rendered](https://github.com/michaelwoerister/rust-forge/blob/review-policy/src/compiler/reviews.md)
@rust-lang/compiler: Please leave comments about anything that you'd still like to have discussed.
=> Update review policy

src/release/triage-procedure.md
based on discussion with @Dylan-DPC
=> explain some more details of the triage procedure

src/triagebot/pr-assignment.md
cc https://github.com/rust-lang/triagebot/pull/1860
=> Add documentation for triagebot default branch warning exceptions

src/SUMMARY.md, src/compiler/reviews.md
Follow-up to #553 for a second round of comments/fixes/improvements.
I applied a few minor cosmetic changes and some wording (feel free to improve how it flows)
=> Review policy changes

src/release/issue-triaging.md
- Document more labels.
- Further clarify / adjust some triage flows.
[Rendered](https://github.com/jieyouxu/rust-forge/blob/label-advice/src/release/issue-triaging.md)
cc @rust-lang/wg-triage
=> Update issue triaging docs

src/SUMMARY.md, src/infra/docs/bors.md, src/infra/docs/bors/queue-resync.md
(a.k.a. bors queue firefighting procedure)
cc https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/try.20jobs.20not.20kicking.20off
[Rendered](https://github.com/jieyouxu/rust-forge/blob/bors-firefighting/src/infra/docs/bors/queue-resync.md)
r? infra
=> bors: document how to properly resync bors queue

src/release/release-notes.md
r? rust-lang/release / cc @rust-lang/release 
cc @RalfJung since you asked for it :)
=> Update release note process for current tooling

src/compiler/mcp.md, src/compiler/membership.md
Reflect the changes made to compiler team structure and organization in RFC 3599.
r? @davidtwco 
[Rendered](https://github.com/wesleywiser/rust-forge/blob/update_membership/src/compiler/mcp.md)
=> Update compiler team membership page

src/release/release-notes.md
[Rendered](https://github.com/Mark-Simulacrum/rust-forge/blob/relnotes-process/src/release/release-notes.md)
=> Add notes about stabilized APIs

src/release/release-notes.md
r? release
[Rendered](https://github.com/jieyouxu/rust-forge/blob/relnotes-interest-group/src/release/release-notes.md)
=> release: document pinging `relnotes-interest-group` for relnotes PRs and relnotes blog posts

src/release/issue-triaging.md
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-3/src/release/issue-triaging.md)
=> document additional labels

src/SUMMARY.md
Currently just shows a blank page, because `community/survey-faq.md` had been removed by #807.
[Rendered](https://github.com/Marcono1234/rust-forge/blob/patch-1/src/SUMMARY.md)
=> Remove "Survey FAQ" deadlink from SUMMARY

src/SUMMARY.md, src/compiler/README.md, src/compiler/meetings.md, src/compiler/operations.md, src/compiler/prioritization.md
This is moving the last remaining bits of T-compiler documentation to the forge.
I have omitted the documentation about the working groupos because I don't have clear what we prefer to do (WGs as a structure seems that will be sunset in the future). My suggestion would be to migrate documentation about WGs in a follow-up PR. Meanwhile I'll figure out which are active and which are not.
[Rendered](https://github.com/apiraino/rust-forge/blob/move-compiler-docs/src/SUMMARY.md)
r? @davidtwco
=> Move to the forge remaining T-compiler docs

src/compiler/proposals-and-stabilization.md
[Rendered](https://github.com/jieyouxu/rust-forge/blob/triagebot-example/src/compiler/proposals-and-stabilization.md)
=> Mention `r? compiler_leads` in adding a new target process

src/release/issue-triaging.md
To make label renames like https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/.E2.9C.94.20Renaming.20label.20.22A-macros-2.2E0.22.20to.20.22A-macros-2-0.22 less likely to be needed again.
Also add a remark about discussing new labels as part of triage.
r? @apiraino 
[Rendered](https://github.com/jieyouxu/rust-forge/blob/label-with-dots/src/release/issue-triaging.md)
=> Document triagebot period-in-label caveat

src/compiler/proposals-and-stabilization.md
This PR adds a procedure when one wants to extend the behavior of a stable flag.
Context for the procedure: https://github.com/rust-lang/rust/pull/138767
r? @davidtwco 
[Rendered](https://github.com/Urgau/rust-forge/blob/extend-behavior-stable-flag/src/compiler/proposals-and-stabilization.md)
=> Add procedure when "Extending the behavior of a stable flag"

src/infra/docs/bastion.md
Looks like docs weren't updated after https://github.com/rust-lang/simpleinfra/pull/578.
[Rendered](https://github.com/Kobzol/rust-forge/blob/bastion-ip-address/src/infra/docs/bastion.md)
=> Remove mention of IP allowlist for bastion

src/SUMMARY.md, src/compiler/README.md, src/compiler/working-areas.md
Follow-up to #814 
I've added a new page about the Working Group, which as an organizational structure will be phased out, so I've tried using "generic" wording. Links to the Zulip channels reflect an upcoming proposal to rename some of them to remove the notion of Working Group.
I've added a list of old and closed WGs for historical purposes, i think it makes sense but let's discuss this.
<details><summary>Screenshot of the new page</summary>
<p>
</p>
</details> 
r? @davidtwco 
[Rendered](https://github.com/apiraino/rust-forge/blob/migrate-docs-wgs/src/SUMMARY.md)
UPDATE: Pending merging of [MCP#848](https://togithub.com/rust-lang/compiler-team/issues/848)
=> Migrate Compiler docs about WGs

src/SUMMARY.md, src/lang/stabilization-procedure.md
Seems like we should copiously cross-link.
=> link to stabilization docs in the rustc-dev-guide

src/compiler/notification-groups.md, src/compiler/prioritization.md, src/compiler/working-areas.md, src/platforms/zulip.md, src/triagebot/zulip-notifications.md
Updated the T-compiler names for Zulip archived channels
r? @davidtwco 
[Rendered](https://github.com/apiraino/rust-forge/blob/update-zulip-channels/src/compiler/notification-groups.md)
=> Update T-compiler zulip channels' names

src/compiler/working-areas.md
This moves to the forge some useful documentation of the (formerly-named) Working Groups that are still active
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
[Rendered](https://github.com/apiraino/rust-forge/blob/add-more-working-areas-refs/src/compiler/working-areas.md)
=> Add more references for compiler working areas

src/SUMMARY.md, src/triagebot/canonicalize-issue-links.md
Implemented in https://github.com/rust-lang/triagebot/pull/1897.
[Rendered](https://github.com/Urgau/rust-forge/blob/canonicalize-issue-links/src/SUMMARY.md)
=> Add documentation for triagebot `[canonicalize-issue-links]` handler

src/SUMMARY.md, src/triagebot/no-mentions.md
Implemented in https://github.com/rust-lang/triagebot/pull/1917
cc @Kobzol 
[Rendered](https://github.com/Urgau/rust-forge/blob/no-mentions/src/SUMMARY.md)
=> Add documentation for triagebot `[no-mentions]` handler

src/compiler/README.md
[Rendered](https://github.com/apiraino/rust-forge/blob/add-compiler-repositories/src/compiler/README.md)
=> Add repositories T-compiler maintains

.github/workflows/deploy.yml, blacksmith/Cargo.lock, blacksmith/Cargo.toml, book.toml
This updates mdbook from 0.4.35 to 0.4.48. There have been a large number of fixes and new features since the last update.
Changelog: https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-0448
=> Update mdbook to 0.4.48

src/SUMMARY.md, src/triagebot/canonicalize-issue-links.md, src/triagebot/issue-links.md
https://github.com/rust-lang/triagebot/pull/1932
[Rendered](https://github.com/Urgau/rust-forge/blob/issue-links/src/SUMMARY.md)
=> Rename triagebot `canonicalize-issue-links` to `issue-links`

src/triagebot/pr-assignment.md
This makes it more precise after https://github.com/rust-lang/triagebot/pull/1937.
[Rendered](https://github.com/Kobzol/rust-forge/blob/triagebot-pr-assignment/src/triagebot/pr-assignment.md)
=> Clarify what enables r? in triagebot

src/release/process.md
Closes #836
@pietroalbini is this the correct fix for the missing link?
thanks
[Rendered](https://github.com/apiraino/rust-forge/blob/fix-link/src/release/process.md)
=> Fix link to AWS CLI

src/SUMMARY.md, src/triagebot/behind-upstream.md
Implemented in https://github.com/rust-lang/triagebot/pull/1942
r? @Urgau 
cc @Kobzol 
[Rendered](https://github.com/xizheyin/rust-forge/blob/behind-upstream/src/SUMMARY.md)
=> Add doc for triagebot [behind-upstream] handler

src/editions/edition-releases.md
This adds a list of steps needed to stabilize an edition. I thought that this checklist existed somewhere, but I couldn't find it, so here it is.
[Rendered](https://github.com/ehuss/rust-forge/blob/stabilizing-an-edition/src/editions/edition-releases.md)
=> Editions: Add checklist on how to stabilize

src/release/issue-triaging.md
cc @jieyouxu 
[Rendered](https://github.com/lolbinarycat/rust-forge/blob/team-roles/src/release/issue-triaging.md)
=> add "Team Roles" section to "Issue Triage" page

src/policies/crate-ownership.md
The current wording makes it sound like Expatriation only applies to Intentional Artifacts but the Council recently clarified that it also applies to Experiments.
From [zulip](https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/Crate.20Ownership.20Policy.20Clarification/near/513732109)
> Just to follow up here, the council discussed this today. Our
> interpretation was that expatriation requires an rfc and council
> approval regardless of its experimental or intentional status (and per
> the policy, is generally discouraged). It may be possible to achieve
> something similar by just forking the project and picking a new name,
> but it sounds like you don't want to go down that route. Working on it
> externally sounds like another alternative. …
=> docs(policy): Clarify that Expatriation applies to all categories

src/platforms/blogs.md
cc https://github.com/rust-lang/blog.rust-lang.org/issues/1013, https://github.com/rust-lang/leadership-council/issues/173
[Rendered](https://github.com/Mark-Simulacrum/rust-forge/blob/blog-updates/src/platforms/blogs.md)
=> Update Blog policy

src/compiler/operations.md
Related to [team#1785](https://github.com/rust-lang/team/pull/1785/files)
> [T-compiler ops]] will prepare meetings agenda, do issue triaging and prioritization, scheduling and documenting meetings.
[Rendered](https://github.com/apiraino/rust-forge/blob/add-t-conmpiler-ops-docs/src/compiler/operations.md)
=> Add T-compiler ops work description

src/triagebot/labeling.md
Related to https://github.com/rust-lang/triagebot/pull/1997
[Rendered](https://github.com/Urgau/rust-forge/blob/relabel-fixes/src/triagebot/labeling.md)
=> Add documentation about quoted labels

src/SUMMARY.md, src/onboarding.md
The lack of this came up in discussion during an all-hands session as a missing artifact. I'm not sure whether this should be in the Forge (but where else?) but seems like an OK starting point. Also probably much more than just this would be helpful.
cc @rust-lang/leadership-council @carols10cents @JakobDegen @rylev @scottmcm @spastorino
[Rendered](https://github.com/Mark-Simulacrum/rust-forge/blob/onboarding-guide/src/SUMMARY.md)
=> Add initial onboarding notes

src/compiler/operations.md, src/compiler/proposals-and-stabilization/ecosystem-integration-tests.md
Just a few links fixed for the T-compiler/ops documentation
thanks!
r? @jieyouxu 
[Rendered](https://github.com/apiraino/rust-forge/blob/fix-linx/src/compiler/operations.md)
=> Fix a few links

src/onboarding.md
cc @Dylan-DPC 
[Rendered](https://github.com/jyn514/rust-forge/blob/joining-teams/src/onboarding.md)
=> add skeleton for how to join a team; suggest joining wg-triage

src/compiler/membership.md
[Rendered](https://github.com/davidtwco/rust-forge/blob/fix-typo/src/compiler/membership.md)
=> fix typo in compiler membership documentation

blacksmith/src/lib.rs, src/infra/other-installation-methods.md
- Delegate to rustup's [*Other installation methods*](https://rust-lang.github.io/rustup/installation/other.html) page.
- Remove `blacksmith` population logic for `rustup-init` listing (`{{#rustup_init_list}}`).
Closes https://github.com/rust-lang/rust-forge/issues/748.
cc @rami3l
r? @ehuss (blacksmith changes)
[Rendered](https://github.com/jieyouxu/rust-forge/blob/rustup-docs/src/infra/other-installation-methods.md)
=> Deduplicate rustup's other installation methods docs by delegating to rustup docs

.github/workflows/deploy.yml, blacksmith/Cargo.lock, blacksmith/Cargo.toml
Diff https://github.com/rust-lang/mdBook/compare/v0.4.48...v0.4.51
More specifically updates (transitively) the `idna` crate.
Hopefully this small update doesn't bring visual breaking changes (https://togithub.com/rust-lang/mdBook/pull/2608 is nice)
=> Update mdbook dependency

src/SUMMARY.md, src/triagebot/concern.md
Related to https://github.com/rust-lang/triagebot/pull/2022.
[Rendered](https://github.com/Urgau/rust-forge/blob/triagebot-concern/src/SUMMARY.md)
=> Add documentation for triagebot `concern` command

src/SUMMARY.md, src/compiler/README.md, src/compiler/backports.md, src/compiler/proposals-and-stabilization.md
> [!TIP]
>
> Part of a meta-effort to document our team policies and processes, cf. [#all-hands-2025 > team processes and policies session](https://rust-lang.zulipchat.com/#narrow/channel/486433-all-hands-2025/topic/team.20processes.20and.20policies.20session/with/519137687).
As part of the async compiler backport experiment, I noticed we didn't really have any concrete docs on how compiler handles backport nominations and decisions (esp. the async process that we're experimenting with now, but also the sync process).
This PR intentionally leaves out specific approvals thresholds because those are still subject to experimentation.
r? @davidtwco (and @wesleywiser)
cc @apiraino (compiler-ops 😁)
cc @cuviper (since you raised the "it's hard (for release team) to determine when to know …
=> Document compiler backport nomination/review process

src/libs/maintaining-std.md
The triagebot docs now live in forge, and the wiki redirects there.
[Rendered](https://github.com/aDotInTheVoid/rust-forge/blob/fix-triagebot-links/src/libs/maintaining-std.md)
=> Fix links to triagebot wiki to be to forge instead

src/compiler/prioritization.md, src/release/issue-triaging.md, src/triagebot/labeling.md, src/triagebot/pinging.md, src/triagebot/transfer.md
Removing the last mentions in our documentation of the WG-prioritization (now replaced by "T-compiler operations") and the unused ICE-breaking ping groups.
These parts of the documentation could benefit from a second read but I'll do it some other time.
r? @jieyouxu
=> Remove last mentions of WG-prioritiation and ICE-breakers ping groups

src/SUMMARY.md, src/wg-rustc-dev-guide/README.md, triagebot.toml
cc @jieyouxu 
[Rendered](https://github.com/rust-lang/rust-forge/blob/dev-guide-page/src/SUMMARY.md)
=> Add a rustc-dev-guide chapter

src/compiler/meetings.md, src/compiler/prioritization.md
From comment: https://github.com/rust-lang/rust-forge/issues/865#issuecomment-2949283516
> The fact that the compiler meetings are purely textual (i.e. without voice / video chat) was strange enough to me that I kept looking for a Google Meet link, even though the docs stated fairly clearly that meetings happen on Zulip.
[Rendered](https://github.com/apiraino/rust-forge/blob/clarify-t-compiler-meetings/src/compiler/meetings.md)
=> Clarify that T-compiler meetings are text-mode only

src/compiler/meetings.md
From [#t-compiler/meetings > Visibility of meetings' notes @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/Visibility.20of.20meetings'.20notes/near/522809889)
thanks @madsmtm !
[Rendered](https://github.com/apiraino/rust-forge/blob/fix-t-compiler-links/src/compiler/meetings.md)
=> Fix t-compiler meetings notes links

src/compiler/proposals-and-stabilization.md
This PR updates the `concern` and `resolve` commands in the MCP section to use `@rustbot` instead, as per https://github.com/rust-lang/compiler-team/pull/880
This also fix the `second` command which was wrongly under `rfcbot`.
r? @apiraino 
[Rendered](https://github.com/Urgau/rust-forge/blob/mcp-update-commands/src/compiler/proposals-and-stabilization.md)
=> Update and fix MCPs commands

.github/workflows/deploy.yml
This switches from rust-lang/simpleinfra/github-actions/static-websites to using GitHub's native actions/deploy-pages to deploy the site. The deploy part of static-websites doesn't seem to be getting updated, and by the discussion at https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Remove.20static-websites.20GitHub.20Action/with/474632056 I get the impression that the infra team would prefer to retire it.
r? marcoieni 
Since you seem to have some context here.
**I think this will need settings changes before merging.** IIUC, static-websites was deploying to a branch, but deploy-pages changes the source. In `Settings > Pages > Build and Deployment > Source` I think the source needs to be changed to "GitHub Actions", though check my understanding since I am uncertain.
=> Use actions/deploy-pages to deploy the website

src/wg-rustc-dev-guide/README.md
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-3/src/wg-rustc-dev-guide/README.md)
=> rgd: fix text regarding rustc-pull merge conflict

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md, book.toml, src/compiler/cross-team-collaboration.md, src/compiler/membership.md, src/compiler/prioritization.md, src/compiler/proposals-and-stabilization.md, src/compiler/reviews.md, src/compiler/third-party-out-of-tree.md, src/compiler/working-areas.md, src/infra/service-infrastructure.md, src/infra/toolstate.md, src/libs/README.md, src/policies/crate-ownership.md
Soo many broken links :laughing:
[Rendered](https://github.com/Kobzol/rust-forge/blob/linkcheck/src/compiler/cross-team-collaboration.md)
=> Add link checking on CI

.github/workflows/deploy.yml
When adding the linkchecker renderer, that changed mdbook to give each renderer a separate path.
=> Fix deploy path

src/infra/docs/aws-access.md
I struggled with this today, so tried to make docs be in a bit better state than I found them :laughing:
[Rendered](https://github.com/Kobzol/rust-forge/blob/aws-configure/src/infra/docs/aws-access.md)
=> Extend guide for configuring legacy AWS access

src/README.md
was thinking of fixing this to say _on Rust Forge GitHub repo_, but then thought lighter wording sounds even better
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-5/src/README.md)
=> readme: be a little less formal

build.bash
`cargo` can now autoconfigure a global build cache either by reading:
- `$CARGO_TARGET_DIR`
- A config file in `~/.cargo`
This entered in a "call for testing" phase recently, see [Twir #602](https://this-week-in-rust.org/blog/2025/06/04/this-week-in-rust-602/#calls-for-testing), so it's available on stable.
The manual override in the build script is not necessary anymore. Instead - it now *prevents* using the global cache in a configuration where `CARGO_TARGET_DIR` is not set but configured in the global cargo config.
=> Enable blacksmith global artifact caching

src/release/process.md
Collected the links I used during this cycle's release preparation.
[Rendered](https://github.com/rust-lang/rust-forge/blob/pa-stable-backports/src/release/process.md)
=> Mention where to look for backports to cherry-pick into stable

.github/workflows/test.yml
This renames the test job to "test" which I think is more descriptive, and also matches the new required-ci checks name.
This fixes merging which no longer works due to https://github.com/rust-lang/team/pull/1870.
=> Rename test job

src/compiler/membership.md
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-8/src/compiler/membership.md)
=> these are already mentioned in preceding paragraph

src/compiler/prioritization.md
As per object. I must have typo'ed the documentation of the triage meeting procedure 
[Rendered](https://github.com/apiraino/rust-forge/blob/fix-links-compiler-backports/src/compiler/prioritization.md)
=> Fix typo to compiler backports list

src/wg-rustc-dev-guide/index.md
cc https://github.com/rust-lang/rustc-dev-guide/pull/2481#issuecomment-3008817712
cc @BoxyUwU 
r? @jieyouxu 
[Rendered](https://github.com/xizheyin/rust-forge/blob/where-contribute/src/wg-rustc-dev-guide/index.md)
=> Explain where rdg changes should be submitted

src/wg-rustc-dev-guide/index.md
[Rendered](https://github.com/tshepang/rust-forge/blob/reuse/src/wg-rustc-dev-guide/index.md)
=> do not dupe link target

src/compiler/proposals-and-stabilization.md, src/infra/other-installation-methods.md
This may sound like incredible bikeshedding :smiley:  but I searched for "tier {1,2,3}" in the compiler proposals page and could not find matches. In my head I am used to identify them as I read in the [Platform Support](https://doc.rust-lang.org/rustc/platform-support.html) page (capitalized word followed by an arabic numeral)
Makes sense?
The second commit slightly clarifies what an FCP is, I'm not 100% sure it's a a widespread enough acronym to give it for granted.
[Rendered](https://github.com/apiraino/rust-forge/blob/consistent-target-tier-naming/src/compiler/proposals-and-stabilization.md)
=> Consistent tiers target naming

src/triagebot/autolabels.md
cc https://github.com/rust-lang/triagebot/pull/2104
r? @Kobzol 
[Rendered](https://github.com/Urgau/rust-forge/blob/triagebot-new_draft/src/triagebot/autolabels.md)
=> Add documentation for triagebot `new_draft` option for autolabels

src/SUMMARY.md, src/triagebot/backport.md
Add documentation for https://github.com/rust-lang/triagebot/pull/2092/, the new triagebot feature that allows auto-nominating a pull request for backport.
[Rendered](https://github.com/apiraino/rust-forge/blob/add-docs-for-automatic-backport-nomination/src/triagebot/backport.md)
=> Add docs about automatic backport nomination

src/compiler/prioritization.md, src/compiler/proposals-and-stabilization.md, src/crates-io/crate-removal.md, src/crates-io/db-maintenance.md, src/docs-rs/maintenance.md, src/docs-rs/self-hosting.md, src/infra/docs/aws-access.md, src/infra/docs/bastion.md, src/infra/docs/crater-agents.md, src/infra/docs/dev-desktop-github-app.md, src/infra/docs/dns.md, src/infra/docs/ecs-services.md, src/infra/docs/rust-bots.md, src/infra/guidelines/static-websites.md, src/infra/policies/broken-nightlies.md, src/infra/service-infrastructure.md, src/release/crater.md, src/release/issue-triaging.md, src/release/process.md, src/release/release-notes.md, src/release/rollups.md, src/triagebot/transfer.md
I noticed that we have a command `mdbook test`, I have run it and discovered a massive quantity of linting errors.
I did a random visual check and adding the `console` parameter to all these quoted texts does not seems to change anything but fixes the tests.
So maybe the question is, are we interested in fixing these tests? Are we using tests here anyway?
thanks for sharing an opinion :)
Note: I left out from this patch some lints failures because they involve Rust code and I suspect it's just not linting
[Rendered](https://github.com/apiraino/rust-forge/blob/fix-tests-round-1/src/crates-io/db-maintenance.md)
=> Fix tests by adding markdown tags

src/docs-rs/self-hosting.md
This PR fixes issue https://github.com/rust-lang/rust-forge/issues/472 
[Rendered](https://github.com/ojuschugh1/rust-forge/blob/fix/ubuntu-version-472/src/docs-rs/self-hosting.md)
=> docs(self-hosting): update Ubuntu LTS from 18.04 to 20.04 (fixes #472)

src/compiler/proposals-and-stabilization.md
The promotion and demotion/removal of targets at different [Target Tiers][target-tier-policy] is currently too coarse. This PR tries to clarify the degree of consensus/approval required for promotions and demotions of targets between different [Target Tiers][target-tier-policy].
r? @davidtwco (or @wesleywiser)
[target-tier-policy]: https://doc.rust-lang.org/rustc/target-tier-policy.html#tier-1-target-policy
[Rendered](https://github.com/jieyouxu/rust-forge/blob/target-demotion/src/compiler/proposals-and-stabilization.md)
=> Clarify required approvals for target promotion and demotion/removal between different target tiers

src/SUMMARY.md, src/triagebot/range-diff.md
cc https://github.com/rust-lang/triagebot/pull/2158
r? Kobzol
[Rendered](https://github.com/Urgau/rust-forge/blob/triagebot-range-diff/src/triagebot/range-diff.md)
=> Add documentation for triagebot new `[range-diff]` handler

src/how-to-start-contributing.md
r? @Kobzol
[Rendered](https://github.com/karolzwolak/rust-forge/blob/remove-useless-link/src/how-to-start-contributing.md)
=> remove duplicate link to rustup repo

src/platforms/blogs.md
This PR clarifies that the list is an OR, instead of an AND.
As discussed in [#t-infra > meeting 2025-08-25 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/meeting.202025-08-25/near/536033048) this isn't clear.
[Rendered](https://github.com/marcoieni/rust-forge/blob/clarify-blogs-approval/src/platforms/blogs.md)
=> clarify blogs approval process

src/triagebot/mentions.md
Related to https://github.com/rust-lang/triagebot/pull/2171
r? Kobzol
[Rendered](https://github.com/Urgau/rust-forge/blob/triagebot-mentions-content/src/triagebot/mentions.md)
=> Add documentation for `type="content"` in triagebot mentions

src/compiler/membership.md
rustc-dev-guide points to bors website itself
[Rendered](https://github.com/rust-lang/rust-forge/blob/tshepang-patch-4/src/compiler/membership.md)
=> point directly to bors docs

src/triagebot/issue-links.md
Related to https://github.com/rust-lang/triagebot/pull/2175
r? Kobzol
[Rendered](https://github.com/Urgau/rust-forge/blob/triagebot-uncanonicalized-issue-links/src/triagebot/issue-links.md)
=> Add documentation for triagebot `check-commits = "uncanonicalized"`

src/release/triage-procedure.md
Context: https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Team-based.20variant.20of.20.60S-waiting-on-team.60/with/542791637
r? @jieyouxu 
[Rendered](https://github.com/Urgau/rust-forge/blob/waiting-on-team-refactor/src/release/triage-procedure.md)
=> Update `S-waiting-on-team` references to new `S-waiting-on-{team}` labels
