rust-lang/rust-forge

- bibliography.md
Adds a link to my master's thesis about using Rust for libpnet.
> Add another paper

- release-process.md
> Release clarifications

- ides.md
Add Visual Studio Code plugins and add `rustfmt` tools
> Add Visual Studio Code plugins

- infrastructure.md
I've tried to mirror the Homu forge docs here. Let me know if anything needs clarification?
> Add info & links for rfcbot.

- platform-support.md
I think this is everything supported today.
r? @alexcrichton @japaric
> More platform support updates

- release-process.md
> Update release process

- cross-compilation/index.html
- cross-compilation/to-windows.md
- index.md
I was chatting with @retep998 the other day about wanting to get "how to cross compile to windows" stuff going. They were kind enough to send me a gist. Here it is.
This is very obviously still a skeleton, but that's what the forge is for! Maybe we can get people excited to fill it out.
> Add cross compilation stuff

- platform-support.md
> add NVPTX and MSP430 to the list of supported targets

- release-process.md
> Update beta instructions

- bibliography.md
> Add a link to a Rust related paper

- ides.md
> Add newline to help markdown parser

- index.md
- pr-triage-procedure.md
Also tries to fix list of status tag meanings.
> Update index.md to link to PR triage procedure.

- beta-backporting.md
- index.md
Taken from irlo.
r? @alexcrichton
> Add text on backporting

- pr-triage-procedure.md
> Add S-inactive-closed documentation.

- pr-triage-procedure.md
> Add issue triage docs

- pr-triage-procedure.md
> Update pr-triage procedure with the C-feature-accepted tag.

- index.md
cc @aturon re our conversation at RustConf
> Add stable release dates to forge homepage

- bibliography.md
A mia culpa following "Ownership is Theft"
> Add "The Case for Writing a Kernel in Rust"

- rustc-team-maintenance.md
@alexcrichton — did you get all of these places? Are the places I forgot to write down?
> Document known places to remove people from

- release-process.md
I've informally been doing the book each release, but we should update dependencies too.
r? @alexcrichton
> Add times to update various things.

- x-py.md
Corrected grammar:
- "may is all you need" -> "may be all you need" and
- "if working...you'll..." -> "if you're working...you'll..."
> edit (grammar): Improve readability of "stage 1" v "stage 2"

- release-process.md
Part of [#46194](https://github.com/rust-lang/rust/issues/46194).
> Adding the Rust By Example documentation to the release process

- release-process.md
Because if T-3 is Monday, then Friday is T-6.
> fix date math

- state-of-rust.md
Suggestion from Reddit so people know how up to date the status is.
> Added Last updated column to state-of-rust

- css/forge.css
> Make table rows have alternating colors

- state-of-rust.md
the date cell for "location of facade crades" was merged itno the status cell
> fix table formatting

- triage-procedure.md
This was proposed in the [last release team meeting](https://mozilla.logbot.info/rust-release).
> Update policy to handle prolonged inactive PRs.

- triage-procedure.md
[Rendered](https://github.com/Aaronepower/rust-forge/blob/help-info/triage-procedure.md#issue-triage)
cc @Mark-Simulacrum
> Added info about handling help issues

- triage-procedure.md
> Document the waiting-on-perf tag

- bibliography.md
- feature-guide.md
Fixes https://github.com/rust-lang-nursery/rust-forge/issues/158
Fixes https://github.com/rust-lang-nursery/rust-forge/issues/164
> Random fixes

- triage-procedure.md
> Add link to the PR Triage Tracking form

- index.md
> Get rid of the while loop that calculates the release date

- platform-support.md
> Remove nacl from the target tiers list.

- triage-procedure.md
r? @pietroalbini / @Mark-Simulacrum 
Also fixed a URL that wasn't properly linkified on the website.
> Add holiday notes to triage procedure.

- release-process.md
> Clarify cargo branches for beta promotion

- rfc-merge-procedure.md
Note: Feel free to squash this PR
r? @Centril
> Update doc and stabilization guide links

- triage-procedure.md
Include `S-waiting-on-fcp` and `S-waiting-on-perf`
> Update the unlabeled PRs link

- release-process.md
> Instructions for invalidating dev-static stable releases

- release-process.md
> Expand on the cargo upload process in the release

- triage-procedure.md
These are around `final-comment-period` and `finshed-final-comment-period` tags
> adding additions to triage procedure as per comments by centril on discord

- src/release/process.md
> Add documentation on how to release on dev-static a try build

- src/lang/triage-meeting-procedure.md
cc @rust-lang/lang -- nothing exciting, but it seemed good to write it down
> document lang-team triage meeting procedure

- src/release/triage-procedure.md
I hope this is keeping the intended meaning.
> triage-procedure: straighten double-negative

- blacksmith/src/lib.rs
Follow-up for rust-lang/rustc-guide#491
> Fix broken link

- .travis.yml
- website_config.json
This was lost in the port, and is now back without the CSP policy as talking with @pietroalbini that might need to be changed.
> Add website_config back without CSP

- src/SUMMARY.md
- src/release/crater.md
cc @Centril @pietroalbini @rust-lang/release 
I'll merge this once feedback dies down (probably around Monday next week, by default). Hopefully we can polish it up a little before then too, happy to take suggestions.
> Document crater triage process

- src/SUMMARY.md
- src/governance/README.md
r? @nikomatsakis 
cc @rust-lang/wg-governance
> Add initial governance section

- src/SUMMARY.md
- src/community/README.md
- src/community/survey-faq.md
Adds the community team, and the survey FAQ to forge. 
cc @rust-lang/community
> Add community team

- src/SUMMARY.md
- src/chat/README.md
- src/chat/discord.md
- src/chat/zulip.md
- src/chat/zulip/moderation.md
> Add documentation about zulip

- src/release/process.md
> [release/process] Comment rustfmt when preparing beta

- src/infra/toolstate.md
Looks like this link got broken when files got moved around.
> fix relative link

- src/SUMMARY.md
- src/github.md
> Add GitHub documentation

- src/SUMMARY.md
- src/chat/email.md
> Add documentation on Email

- src/chat/discord.md
This documentation does not describe how to set up channels, but is otherwise probably sufficient to get newcomers started.
I'd like to add an animated GIF to make accessing the Notifications menu clearer, but cannot upload files. right now there is a placeholder -IMAGE GOES HERE-.
> Initial Discord documentation

- js/index.js
- src/README.md
Let's say nightly is 1.43, then "next" is 1.44.
r? @XAMPPRocky
> Add "next" row after "nightly"

- README.md
> Add documentation on adding teams to forge.

- src/docs-rs/add-dependencies.md
Found in https://github.com/rust-lang/docs.rs/issues/630#issuecomment-603171676
> [docs.rs] Fix incorrect environment variable

- .github/workflows/deploy.yml
This requires `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to be set in secrets. You can see an example of this running here. https://github.com/XAMPPRocky/rust-forge/runs/560904891
> Add GitHub Actions

- src/infra/service-infrastructure.md
This direct link saves a bunch of wondering whether I can find the information I am looking for on https://github.com/rust-lang/crater. :)
> link to crater bot docs

- src/SUMMARY.md
- src/compiler/membership.md
- src/compiler/reviews.md
This mostly just adds material from RFC 2689
> document compiler member and contributors

- src/release/triage-procedure.md
Filter out draft PRs from search queries for S-waiting-on-review and S-waiting-on-author links.
> Update triage-procedure.md - filter out drafts

- src/SUMMARY.md
- src/core/legal.md
> Add legal counsel page

- src/crates-io/crate-removal.md
> Update crates.io crate removal procedures

- src/SUMMARY.md
- src/compiler/new_option.md
> document the procedure for adding a new option to rustc

- src/compiler/reviews.md
Discussion https://rust-lang.zulipchat.com/#narrow/pm-with/116009-user116009
> Suggest to bump priority of high priority PRs

- src/infra/docs/ecs-services.md
> infra: add documentation on rolling back ecs services

- src/SUMMARY.md
- src/infra/docs/gha-self-hosted.md
@Mark-Simulacrum do you feel there is something else I need to document about the self-hosted runners?
> infra: add documentation for gha-self-hosted

- src/docs-rs/maintenance.md
> Document how to deprioritize crates

- src/compiler/prioritization/procedure.md
cc @rust-lang/wg-prioritization
> Minor tweaks about WG-Prioritization procedure

- src/compiler/prioritization/procedure.md
Found them in reviewing #405.
r? @XAMPPRocky
> Fix minor issues in prioritization procedure

- src/compiler/notification-groups.md
The diff is noisy a bit as this also contains some style fixes.
r? @nikomatsakis
> Mention Zulip stream in notification group TODO list

- src/compiler/prioritization/procedure.md
Explain a bit better the Prioritization summarize process
cc @rust-lang/wg-prioritization 
Please fix my english if it's broken :)
> Improve Prioritization procedure's summarize sections

- src/compiler/prioritization/procedure.md
cc @rust-lang/wg-prioritization
> Fix prioritization FCP/MCP section

- src/compiler/prioritization/procedure.md
> Fix I-nominated link

- src/compiler/prioritization/procedure.md
> Use <time instead of 2pm UTC to message Zulip

- src/compiler/prioritization/procedure.md
> Add more prioritization following steps

- src/compiler/prioritization/procedure.md
> Add 'Copy content from last week' text to prioritization procedure

- src/compiler/prioritization/procedure.md
> The command was changed to prioritization-agenda

- src/compiler/prioritization/procedure.md
> List issues to add team labels when there's no team

- src/compiler/prioritization/procedure.md
cc @rust-lang/wg-prioritization
> Move remove to announce steps to follow ups from previous meeting

- src/compiler/prioritization/procedure.md
> Place prioritization procedure first things, first

- src/compiler/prioritization/procedure.md
https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/2020-09-24.20meeting.20agenda/near/211028602
r? @spastorino
> Don't ping WG-prioritization as much in weekly meetings

- src/platforms/zulip/triagebot.md
See rust-lang/triagebot#871 for the command's implementation.
Cc @Mark-Simulacrum
> Update triagebot page for `ack all`

- src/compiler/prioritization/procedure.md
This sorts better what we do in the follow ups.
r? @XAMPPRocky
> Reorder prioritization followups better

- src/release/process.md
This PR changes the release process documentation to make use of the new tooling.
r? @Mark-Simulacrum
> Update the release process to use the new promote-release

- src/infra/docs/dns.md
> Add documentaiton on transferring domains

- src/infra/docs/gha-self-hosted.md
Needed to do this today, let's document how I did it in case we need to redo it in the future.
r? @Mark-Simulacrum
> Document how to access the out-of-band console of ci-arm-1

- src/infra/docs/gha-self-hosted.md
> Add documentation on how to bump the GHA runner

- src/compiler/prioritization/procedure.md
cc @rust-lang/wg-prioritization 
:facepalm: look at what was the issue
This superseeds #484
> Fix no team filters

- src/compiler/prioritization/procedure.md
The label appears to have been renamed recently.
> Change all uses of `libs-impl` to `T-libs-impl`

- src/release/triage-procedure.md
> Clarify unclear language in Triage Procedure

- src/SUMMARY.md
- src/crates-io/db-maintenance.md
Finally got the time to put down the checklist we use for database maintenance on crates.io.
r? @jtgeibel
> Add crates.io database maintenance checklist

- src/infra/docs/bors.md
> Update the instructions on setting up bors

- src/crates-io/db-maintenance.md
Derived from the last maintenance's checklist.
r? @jtgeibel
> Add instructions for performing crates.io follower maintenance

- src/release/process.md
> Update release process to use new scripts from simpleinfra

- src/SUMMARY.md
- src/core/twitter.md
These were previously already published as tweets:
https://twitter.com/rustlang/status/1263105812064620545
> Put Twitter guidelines into writing

- src/SUMMARY.md
- src/infra/docs/dev-desktop-github-app.md
The implementation is happening at https://github.com/rust-lang/simpleinfra/pull/79
> Move docs over from infra repo

- .github/workflows/deploy.yml
- Move CI to OIDC role assumption
- Grant access to token
> Add token permissions

- src/release/process.md
> release/process: clarify branch forking vs promotion

- src/infra/docs/rustc-ci.md
The CI docs are largely up to date but were missing some additional information.
*Based on a conversation with @pietroalbini and @jdno*
> Improve CI docs

- src/README.md
Cargo recently changed its labeling for issues that are soliciting for help.
> Update cargo help-wanted

- src/triagebot/autolabels.md
Document the changes in https://github.com/rust-lang/triagebot/pull/1708
> Document triagebot `new_issue`

- src/infra/docs/dev-desktop.md
related to rust-lang/simpleinfra#335
> feat(dev-dekstop): explain user shell customization 📝

- src/archive/release-history.md
Closes #695.
See also rust-lang/www.rust-lang.org#1851.
> Update URLs for GPG signing keys

- src/SUMMARY.md
- src/editions/edition-releases.md
This adds some documentation on how an Edition release works.
> Add chapter on running Edition releases.

- src/compiler/prioritization/procedure.md
Updating the documentation because of this https://github.com/rust-lang/triagebot/issues/1789
> Tiny update about triagebot usage

- src/editions/edition-releases.md
mdBook is another tool that needs edition support.
> Include mdbook in list of tools that need edition support.

- .github/workflows/deploy.yml
- blacksmith/src/channel.rs
- blacksmith/src/lib.rs
- book.toml
The changes are minor so I don't feel too strongly about them. It's just so close to being "correctly" formatted that we may as well go the rest of the way.
> Format some files

- src/infra/docs/bastion.md
I removed a repeated paragraph.
Looks better to me now!
> Improve bastion IP docs

- src/community/survey-faq.md
I forgot to add them here after the results were published in February.
> Add link to Rust 2023 annual survey results

- src/release/process.md
This PR updates the release process with the pieces of feedback Boxy gave me after the last release.
r? @Mark-Simulacrum 
cc @cuviper
> Update the release process with Boxy's feedback

- src/release/process.md
> Fix a link in process.md

- triagebot.toml
https://forge.rust-lang.org/triagebot/rendered-link.html
> Automatically add rendered link to pull-requests

- src/release/release-notes.md
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-5/src/release/release-notes.md)
> make link clickable

- src/compiler/membership.md
[Rendered](https://github.com/hkBst/rust-forge/blob/patch-1/src/compiler/membership.md)
> most important criter{ia => ion}

- src/triagebot/canonicalize-issue-links.md
[Rendered](https://github.com/tshepang/rust-forge/blob/patch-3/src/triagebot/canonicalize-issue-links.md)
> canonicalize-issue-links.md: improve readability

- triagebot.toml
This sets the review rotation to the edition team.
> Set edition assignments to the edition team

- src/infra/docs/dev-desktop.md
[Rendered](https://github.com/KMJ-007/rust-forge/blob/patch-1/src/infra/docs/dev-desktop.md)
> updated docs regarding dev desktop: github account id is case sensitive

- src/triagebot/issue-links.md
Added in https://github.com/rust-lang/triagebot/pull/1966
[Rendered](https://github.com/Urgau/rust-forge/blob/issue-links-wo-commits/src/triagebot/issue-links.md)
> Mention `check-commits = false` for triagebot `[issue-links]`

- .github/workflows/deploy.yml
probably won't fix the error on master, but worth trying.
> update configure-aws-credentials action

- src/infra/docs/crater-agents.md
- src/infra/docs/docs-rs.md
- src/infra/docs/monitoring.md
- src/infra/docs/rust-bots.md
[Rendered](https://github.com/cyrgani/rust-forge/blob/bastion/src/infra/docs/crater-agents.md)
> fix links for bastion login

- src/infra/docs/dev-desktop.md
[Rendered](https://github.com/clubby789/rust-forge/blob/decomissioned/src/infra/docs/dev-desktop.md)
> Mention decomissioned `*-2` dev desktops

- src/archive/release-history.md
- src/compiler/backports.md
- src/compiler/third-party-out-of-tree.md
- src/compiler/working-areas.md
- src/infra/docs/bors/queue-resync.md
- src/infra/docs/rustc-ci.md
- src/infra/toolstate.md
- src/libs/maintaining-std.md
- src/release/issue-triaging.md
- src/release/process.md
- src/release/rollups.md
- src/triagebot/github-releases.md
- src/triagebot/index.md
- src/triagebot/no-merge.md
- src/triagebot/pinging.md
- src/triagebot/pr-assignment.md
https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Renaming.20the.20master.20branch.20for.20rust-lang.2Frust/with/537642075
[Rendered](https://github.com/Kobzol/rust-forge/blob/remove-master-dependency/src/release/process.md)
> Replace hardcoded references to master

- src/infra/docs/bors.md
was https://github.com/rust-lang/rust-forge/pull/948
[Rendered](https://github.com/rust-lang/rust-forge/blob/tshepang-patch-3/src/infra/docs/bors.md)
> only rust-lang/rust uses bors now

- src/infra/team-maintenance.md
[Rendered](https://github.com/rust-lang/rust-forge/blob/tshepang-patch-2/src/infra/team-maintenance.md)
> team-maintenance.md: fix intro paragraph
